import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { ReactNode } from "react";
import { Footer } from "./components/Footer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode; // Type for children prop
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased dark`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
